/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE19Args } from "./DeleteE19Args";
import { E19FindManyArgs } from "./E19FindManyArgs";
import { E19FindUniqueArgs } from "./E19FindUniqueArgs";
import { E19 } from "./E19";
import { E19Service } from "../e19.service";

@graphql.Resolver(() => E19)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E19ResolverBase {
  constructor(
    protected readonly service: E19Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E19",
    action: "read",
    possession: "any",
  })
  async _e19sMeta(
    @graphql.Args() args: E19FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E19])
  @nestAccessControl.UseRoles({
    resource: "E19",
    action: "read",
    possession: "any",
  })
  async e19s(@graphql.Args() args: E19FindManyArgs): Promise<E19[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E19, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E19",
    action: "read",
    possession: "own",
  })
  async e19(@graphql.Args() args: E19FindUniqueArgs): Promise<E19 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E19)
  @nestAccessControl.UseRoles({
    resource: "E19",
    action: "delete",
    possession: "any",
  })
  async deleteE19(@graphql.Args() args: DeleteE19Args): Promise<E19 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
