/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE55Args } from "./DeleteE55Args";
import { E55FindManyArgs } from "./E55FindManyArgs";
import { E55FindUniqueArgs } from "./E55FindUniqueArgs";
import { E55 } from "./E55";
import { E55Service } from "../e55.service";

@graphql.Resolver(() => E55)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E55ResolverBase {
  constructor(
    protected readonly service: E55Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E55",
    action: "read",
    possession: "any",
  })
  async _e55sMeta(
    @graphql.Args() args: E55FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E55])
  @nestAccessControl.UseRoles({
    resource: "E55",
    action: "read",
    possession: "any",
  })
  async e55s(@graphql.Args() args: E55FindManyArgs): Promise<E55[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E55, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E55",
    action: "read",
    possession: "own",
  })
  async e55(@graphql.Args() args: E55FindUniqueArgs): Promise<E55 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E55)
  @nestAccessControl.UseRoles({
    resource: "E55",
    action: "delete",
    possession: "any",
  })
  async deleteE55(@graphql.Args() args: DeleteE55Args): Promise<E55 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
