/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE43Args } from "./DeleteE43Args";
import { E43FindManyArgs } from "./E43FindManyArgs";
import { E43FindUniqueArgs } from "./E43FindUniqueArgs";
import { E43 } from "./E43";
import { E43Service } from "../e43.service";

@graphql.Resolver(() => E43)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E43ResolverBase {
  constructor(
    protected readonly service: E43Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E43",
    action: "read",
    possession: "any",
  })
  async _e43sMeta(
    @graphql.Args() args: E43FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E43])
  @nestAccessControl.UseRoles({
    resource: "E43",
    action: "read",
    possession: "any",
  })
  async e43s(@graphql.Args() args: E43FindManyArgs): Promise<E43[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E43, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E43",
    action: "read",
    possession: "own",
  })
  async e43(@graphql.Args() args: E43FindUniqueArgs): Promise<E43 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E43)
  @nestAccessControl.UseRoles({
    resource: "E43",
    action: "delete",
    possession: "any",
  })
  async deleteE43(@graphql.Args() args: DeleteE43Args): Promise<E43 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
