/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE33Args } from "./DeleteE33Args";
import { E33FindManyArgs } from "./E33FindManyArgs";
import { E33FindUniqueArgs } from "./E33FindUniqueArgs";
import { E33 } from "./E33";
import { E33Service } from "../e33.service";

@graphql.Resolver(() => E33)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E33ResolverBase {
  constructor(
    protected readonly service: E33Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E33",
    action: "read",
    possession: "any",
  })
  async _e33sMeta(
    @graphql.Args() args: E33FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E33])
  @nestAccessControl.UseRoles({
    resource: "E33",
    action: "read",
    possession: "any",
  })
  async e33s(@graphql.Args() args: E33FindManyArgs): Promise<E33[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E33, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E33",
    action: "read",
    possession: "own",
  })
  async e33(@graphql.Args() args: E33FindUniqueArgs): Promise<E33 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E33)
  @nestAccessControl.UseRoles({
    resource: "E33",
    action: "delete",
    possession: "any",
  })
  async deleteE33(@graphql.Args() args: DeleteE33Args): Promise<E33 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
