/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE66Args } from "./DeleteE66Args";
import { E66FindManyArgs } from "./E66FindManyArgs";
import { E66FindUniqueArgs } from "./E66FindUniqueArgs";
import { E66 } from "./E66";
import { E66Service } from "../e66.service";

@graphql.Resolver(() => E66)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E66ResolverBase {
  constructor(
    protected readonly service: E66Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E66",
    action: "read",
    possession: "any",
  })
  async _e66sMeta(
    @graphql.Args() args: E66FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E66])
  @nestAccessControl.UseRoles({
    resource: "E66",
    action: "read",
    possession: "any",
  })
  async e66s(@graphql.Args() args: E66FindManyArgs): Promise<E66[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E66, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E66",
    action: "read",
    possession: "own",
  })
  async e66(@graphql.Args() args: E66FindUniqueArgs): Promise<E66 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E66)
  @nestAccessControl.UseRoles({
    resource: "E66",
    action: "delete",
    possession: "any",
  })
  async deleteE66(@graphql.Args() args: DeleteE66Args): Promise<E66 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
