/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE25Args } from "./DeleteE25Args";
import { E25FindManyArgs } from "./E25FindManyArgs";
import { E25FindUniqueArgs } from "./E25FindUniqueArgs";
import { E25 } from "./E25";
import { E25Service } from "../e25.service";

@graphql.Resolver(() => E25)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E25ResolverBase {
  constructor(
    protected readonly service: E25Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E25",
    action: "read",
    possession: "any",
  })
  async _e25sMeta(
    @graphql.Args() args: E25FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E25])
  @nestAccessControl.UseRoles({
    resource: "E25",
    action: "read",
    possession: "any",
  })
  async e25s(@graphql.Args() args: E25FindManyArgs): Promise<E25[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E25, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E25",
    action: "read",
    possession: "own",
  })
  async e25(@graphql.Args() args: E25FindUniqueArgs): Promise<E25 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E25)
  @nestAccessControl.UseRoles({
    resource: "E25",
    action: "delete",
    possession: "any",
  })
  async deleteE25(@graphql.Args() args: DeleteE25Args): Promise<E25 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
