/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE70Args } from "./DeleteE70Args";
import { E70FindManyArgs } from "./E70FindManyArgs";
import { E70FindUniqueArgs } from "./E70FindUniqueArgs";
import { E70 } from "./E70";
import { E70Service } from "../e70.service";

@graphql.Resolver(() => E70)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E70ResolverBase {
  constructor(
    protected readonly service: E70Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E70",
    action: "read",
    possession: "any",
  })
  async _e70sMeta(
    @graphql.Args() args: E70FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E70])
  @nestAccessControl.UseRoles({
    resource: "E70",
    action: "read",
    possession: "any",
  })
  async e70s(@graphql.Args() args: E70FindManyArgs): Promise<E70[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E70, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E70",
    action: "read",
    possession: "own",
  })
  async e70(@graphql.Args() args: E70FindUniqueArgs): Promise<E70 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E70)
  @nestAccessControl.UseRoles({
    resource: "E70",
    action: "delete",
    possession: "any",
  })
  async deleteE70(@graphql.Args() args: DeleteE70Args): Promise<E70 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
