/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE49Args } from "./DeleteE49Args";
import { E49FindManyArgs } from "./E49FindManyArgs";
import { E49FindUniqueArgs } from "./E49FindUniqueArgs";
import { E49 } from "./E49";
import { E49Service } from "../e49.service";

@graphql.Resolver(() => E49)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E49ResolverBase {
  constructor(
    protected readonly service: E49Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E49",
    action: "read",
    possession: "any",
  })
  async _e49sMeta(
    @graphql.Args() args: E49FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E49])
  @nestAccessControl.UseRoles({
    resource: "E49",
    action: "read",
    possession: "any",
  })
  async e49s(@graphql.Args() args: E49FindManyArgs): Promise<E49[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E49, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E49",
    action: "read",
    possession: "own",
  })
  async e49(@graphql.Args() args: E49FindUniqueArgs): Promise<E49 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E49)
  @nestAccessControl.UseRoles({
    resource: "E49",
    action: "delete",
    possession: "any",
  })
  async deleteE49(@graphql.Args() args: DeleteE49Args): Promise<E49 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
