/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE61Args } from "./DeleteE61Args";
import { E61FindManyArgs } from "./E61FindManyArgs";
import { E61FindUniqueArgs } from "./E61FindUniqueArgs";
import { E61 } from "./E61";
import { E61Service } from "../e61.service";

@graphql.Resolver(() => E61)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E61ResolverBase {
  constructor(
    protected readonly service: E61Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E61",
    action: "read",
    possession: "any",
  })
  async _e61sMeta(
    @graphql.Args() args: E61FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E61])
  @nestAccessControl.UseRoles({
    resource: "E61",
    action: "read",
    possession: "any",
  })
  async e61s(@graphql.Args() args: E61FindManyArgs): Promise<E61[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E61, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E61",
    action: "read",
    possession: "own",
  })
  async e61(@graphql.Args() args: E61FindUniqueArgs): Promise<E61 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E61)
  @nestAccessControl.UseRoles({
    resource: "E61",
    action: "delete",
    possession: "any",
  })
  async deleteE61(@graphql.Args() args: DeleteE61Args): Promise<E61 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
