/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE52Args } from "./DeleteE52Args";
import { E52FindManyArgs } from "./E52FindManyArgs";
import { E52FindUniqueArgs } from "./E52FindUniqueArgs";
import { E52 } from "./E52";
import { E52Service } from "../e52.service";

@graphql.Resolver(() => E52)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E52ResolverBase {
  constructor(
    protected readonly service: E52Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E52",
    action: "read",
    possession: "any",
  })
  async _e52sMeta(
    @graphql.Args() args: E52FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E52])
  @nestAccessControl.UseRoles({
    resource: "E52",
    action: "read",
    possession: "any",
  })
  async e52s(@graphql.Args() args: E52FindManyArgs): Promise<E52[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E52, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E52",
    action: "read",
    possession: "own",
  })
  async e52(@graphql.Args() args: E52FindUniqueArgs): Promise<E52 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E52)
  @nestAccessControl.UseRoles({
    resource: "E52",
    action: "delete",
    possession: "any",
  })
  async deleteE52(@graphql.Args() args: DeleteE52Args): Promise<E52 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
