/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE24Args } from "./DeleteE24Args";
import { E24FindManyArgs } from "./E24FindManyArgs";
import { E24FindUniqueArgs } from "./E24FindUniqueArgs";
import { E24 } from "./E24";
import { E24Service } from "../e24.service";

@graphql.Resolver(() => E24)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E24ResolverBase {
  constructor(
    protected readonly service: E24Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E24",
    action: "read",
    possession: "any",
  })
  async _e24sMeta(
    @graphql.Args() args: E24FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E24])
  @nestAccessControl.UseRoles({
    resource: "E24",
    action: "read",
    possession: "any",
  })
  async e24s(@graphql.Args() args: E24FindManyArgs): Promise<E24[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E24, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E24",
    action: "read",
    possession: "own",
  })
  async e24(@graphql.Args() args: E24FindUniqueArgs): Promise<E24 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E24)
  @nestAccessControl.UseRoles({
    resource: "E24",
    action: "delete",
    possession: "any",
  })
  async deleteE24(@graphql.Args() args: DeleteE24Args): Promise<E24 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
