/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE8Args } from "./DeleteE8Args";
import { E8FindManyArgs } from "./E8FindManyArgs";
import { E8FindUniqueArgs } from "./E8FindUniqueArgs";
import { E8 } from "./E8";
import { E8Service } from "../e8.service";

@graphql.Resolver(() => E8)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E8ResolverBase {
  constructor(
    protected readonly service: E8Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E8",
    action: "read",
    possession: "any",
  })
  async _e8sMeta(
    @graphql.Args() args: E8FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E8])
  @nestAccessControl.UseRoles({
    resource: "E8",
    action: "read",
    possession: "any",
  })
  async e8s(@graphql.Args() args: E8FindManyArgs): Promise<E8[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E8, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E8",
    action: "read",
    possession: "own",
  })
  async e8(@graphql.Args() args: E8FindUniqueArgs): Promise<E8 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E8)
  @nestAccessControl.UseRoles({
    resource: "E8",
    action: "delete",
    possession: "any",
  })
  async deleteE8(@graphql.Args() args: DeleteE8Args): Promise<E8 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
