/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE37Args } from "./DeleteE37Args";
import { E37FindManyArgs } from "./E37FindManyArgs";
import { E37FindUniqueArgs } from "./E37FindUniqueArgs";
import { E37 } from "./E37";
import { E37Service } from "../e37.service";

@graphql.Resolver(() => E37)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E37ResolverBase {
  constructor(
    protected readonly service: E37Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E37",
    action: "read",
    possession: "any",
  })
  async _e37sMeta(
    @graphql.Args() args: E37FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E37])
  @nestAccessControl.UseRoles({
    resource: "E37",
    action: "read",
    possession: "any",
  })
  async e37s(@graphql.Args() args: E37FindManyArgs): Promise<E37[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E37, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E37",
    action: "read",
    possession: "own",
  })
  async e37(@graphql.Args() args: E37FindUniqueArgs): Promise<E37 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E37)
  @nestAccessControl.UseRoles({
    resource: "E37",
    action: "delete",
    possession: "any",
  })
  async deleteE37(@graphql.Args() args: DeleteE37Args): Promise<E37 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
