/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE28Args } from "./DeleteE28Args";
import { E28FindManyArgs } from "./E28FindManyArgs";
import { E28FindUniqueArgs } from "./E28FindUniqueArgs";
import { E28 } from "./E28";
import { E28Service } from "../e28.service";

@graphql.Resolver(() => E28)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E28ResolverBase {
  constructor(
    protected readonly service: E28Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E28",
    action: "read",
    possession: "any",
  })
  async _e28sMeta(
    @graphql.Args() args: E28FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E28])
  @nestAccessControl.UseRoles({
    resource: "E28",
    action: "read",
    possession: "any",
  })
  async e28s(@graphql.Args() args: E28FindManyArgs): Promise<E28[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E28, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E28",
    action: "read",
    possession: "own",
  })
  async e28(@graphql.Args() args: E28FindUniqueArgs): Promise<E28 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E28)
  @nestAccessControl.UseRoles({
    resource: "E28",
    action: "delete",
    possession: "any",
  })
  async deleteE28(@graphql.Args() args: DeleteE28Args): Promise<E28 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
