/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE11Args } from "./DeleteE11Args";
import { E11FindManyArgs } from "./E11FindManyArgs";
import { E11FindUniqueArgs } from "./E11FindUniqueArgs";
import { E11 } from "./E11";
import { E11Service } from "../e11.service";

@graphql.Resolver(() => E11)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E11ResolverBase {
  constructor(
    protected readonly service: E11Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E11",
    action: "read",
    possession: "any",
  })
  async _e11sMeta(
    @graphql.Args() args: E11FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E11])
  @nestAccessControl.UseRoles({
    resource: "E11",
    action: "read",
    possession: "any",
  })
  async e11s(@graphql.Args() args: E11FindManyArgs): Promise<E11[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E11, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E11",
    action: "read",
    possession: "own",
  })
  async e11(@graphql.Args() args: E11FindUniqueArgs): Promise<E11 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E11)
  @nestAccessControl.UseRoles({
    resource: "E11",
    action: "delete",
    possession: "any",
  })
  async deleteE11(@graphql.Args() args: DeleteE11Args): Promise<E11 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
