/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE27Args } from "./DeleteE27Args";
import { E27FindManyArgs } from "./E27FindManyArgs";
import { E27FindUniqueArgs } from "./E27FindUniqueArgs";
import { E27 } from "./E27";
import { E27Service } from "../e27.service";

@graphql.Resolver(() => E27)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E27ResolverBase {
  constructor(
    protected readonly service: E27Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E27",
    action: "read",
    possession: "any",
  })
  async _e27sMeta(
    @graphql.Args() args: E27FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E27])
  @nestAccessControl.UseRoles({
    resource: "E27",
    action: "read",
    possession: "any",
  })
  async e27s(@graphql.Args() args: E27FindManyArgs): Promise<E27[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E27, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E27",
    action: "read",
    possession: "own",
  })
  async e27(@graphql.Args() args: E27FindUniqueArgs): Promise<E27 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E27)
  @nestAccessControl.UseRoles({
    resource: "E27",
    action: "delete",
    possession: "any",
  })
  async deleteE27(@graphql.Args() args: DeleteE27Args): Promise<E27 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
