/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE5Args } from "./DeleteE5Args";
import { E5FindManyArgs } from "./E5FindManyArgs";
import { E5FindUniqueArgs } from "./E5FindUniqueArgs";
import { E5 } from "./E5";
import { E5Service } from "../e5.service";

@graphql.Resolver(() => E5)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E5ResolverBase {
  constructor(
    protected readonly service: E5Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E5",
    action: "read",
    possession: "any",
  })
  async _e5sMeta(
    @graphql.Args() args: E5FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E5])
  @nestAccessControl.UseRoles({
    resource: "E5",
    action: "read",
    possession: "any",
  })
  async e5s(@graphql.Args() args: E5FindManyArgs): Promise<E5[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E5, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E5",
    action: "read",
    possession: "own",
  })
  async e5(@graphql.Args() args: E5FindUniqueArgs): Promise<E5 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E5)
  @nestAccessControl.UseRoles({
    resource: "E5",
    action: "delete",
    possession: "any",
  })
  async deleteE5(@graphql.Args() args: DeleteE5Args): Promise<E5 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
