/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE12Args } from "./DeleteE12Args";
import { E12FindManyArgs } from "./E12FindManyArgs";
import { E12FindUniqueArgs } from "./E12FindUniqueArgs";
import { E12 } from "./E12";
import { E12Service } from "../e12.service";

@graphql.Resolver(() => E12)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E12ResolverBase {
  constructor(
    protected readonly service: E12Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E12",
    action: "read",
    possession: "any",
  })
  async _e12sMeta(
    @graphql.Args() args: E12FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E12])
  @nestAccessControl.UseRoles({
    resource: "E12",
    action: "read",
    possession: "any",
  })
  async e12s(@graphql.Args() args: E12FindManyArgs): Promise<E12[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E12, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E12",
    action: "read",
    possession: "own",
  })
  async e12(@graphql.Args() args: E12FindUniqueArgs): Promise<E12 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E12)
  @nestAccessControl.UseRoles({
    resource: "E12",
    action: "delete",
    possession: "any",
  })
  async deleteE12(@graphql.Args() args: DeleteE12Args): Promise<E12 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
