/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE53Args } from "./DeleteE53Args";
import { E53FindManyArgs } from "./E53FindManyArgs";
import { E53FindUniqueArgs } from "./E53FindUniqueArgs";
import { E53 } from "./E53";
import { E53Service } from "../e53.service";

@graphql.Resolver(() => E53)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E53ResolverBase {
  constructor(
    protected readonly service: E53Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E53",
    action: "read",
    possession: "any",
  })
  async _e53sMeta(
    @graphql.Args() args: E53FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E53])
  @nestAccessControl.UseRoles({
    resource: "E53",
    action: "read",
    possession: "any",
  })
  async e53s(@graphql.Args() args: E53FindManyArgs): Promise<E53[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E53, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E53",
    action: "read",
    possession: "own",
  })
  async e53(@graphql.Args() args: E53FindUniqueArgs): Promise<E53 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E53)
  @nestAccessControl.UseRoles({
    resource: "E53",
    action: "delete",
    possession: "any",
  })
  async deleteE53(@graphql.Args() args: DeleteE53Args): Promise<E53 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
