/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE31Args } from "./DeleteE31Args";
import { E31FindManyArgs } from "./E31FindManyArgs";
import { E31FindUniqueArgs } from "./E31FindUniqueArgs";
import { E31 } from "./E31";
import { E31Service } from "../e31.service";

@graphql.Resolver(() => E31)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E31ResolverBase {
  constructor(
    protected readonly service: E31Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E31",
    action: "read",
    possession: "any",
  })
  async _e31sMeta(
    @graphql.Args() args: E31FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E31])
  @nestAccessControl.UseRoles({
    resource: "E31",
    action: "read",
    possession: "any",
  })
  async e31s(@graphql.Args() args: E31FindManyArgs): Promise<E31[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E31, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E31",
    action: "read",
    possession: "own",
  })
  async e31(@graphql.Args() args: E31FindUniqueArgs): Promise<E31 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E31)
  @nestAccessControl.UseRoles({
    resource: "E31",
    action: "delete",
    possession: "any",
  })
  async deleteE31(@graphql.Args() args: DeleteE31Args): Promise<E31 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
