/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE59Args } from "./DeleteE59Args";
import { E59FindManyArgs } from "./E59FindManyArgs";
import { E59FindUniqueArgs } from "./E59FindUniqueArgs";
import { E59 } from "./E59";
import { E59Service } from "../e59.service";

@graphql.Resolver(() => E59)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E59ResolverBase {
  constructor(
    protected readonly service: E59Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E59",
    action: "read",
    possession: "any",
  })
  async _e59sMeta(
    @graphql.Args() args: E59FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E59])
  @nestAccessControl.UseRoles({
    resource: "E59",
    action: "read",
    possession: "any",
  })
  async e59s(@graphql.Args() args: E59FindManyArgs): Promise<E59[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E59, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E59",
    action: "read",
    possession: "own",
  })
  async e59(@graphql.Args() args: E59FindUniqueArgs): Promise<E59 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E59)
  @nestAccessControl.UseRoles({
    resource: "E59",
    action: "delete",
    possession: "any",
  })
  async deleteE59(@graphql.Args() args: DeleteE59Args): Promise<E59 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
