/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE18Args } from "./DeleteE18Args";
import { E18FindManyArgs } from "./E18FindManyArgs";
import { E18FindUniqueArgs } from "./E18FindUniqueArgs";
import { E18 } from "./E18";
import { E18Service } from "../e18.service";

@graphql.Resolver(() => E18)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E18ResolverBase {
  constructor(
    protected readonly service: E18Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E18",
    action: "read",
    possession: "any",
  })
  async _e18sMeta(
    @graphql.Args() args: E18FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E18])
  @nestAccessControl.UseRoles({
    resource: "E18",
    action: "read",
    possession: "any",
  })
  async e18s(@graphql.Args() args: E18FindManyArgs): Promise<E18[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E18, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E18",
    action: "read",
    possession: "own",
  })
  async e18(@graphql.Args() args: E18FindUniqueArgs): Promise<E18 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E18)
  @nestAccessControl.UseRoles({
    resource: "E18",
    action: "delete",
    possession: "any",
  })
  async deleteE18(@graphql.Args() args: DeleteE18Args): Promise<E18 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
