/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE30Args } from "./DeleteE30Args";
import { E30FindManyArgs } from "./E30FindManyArgs";
import { E30FindUniqueArgs } from "./E30FindUniqueArgs";
import { E30 } from "./E30";
import { E30Service } from "../e30.service";

@graphql.Resolver(() => E30)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E30ResolverBase {
  constructor(
    protected readonly service: E30Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E30",
    action: "read",
    possession: "any",
  })
  async _e30sMeta(
    @graphql.Args() args: E30FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E30])
  @nestAccessControl.UseRoles({
    resource: "E30",
    action: "read",
    possession: "any",
  })
  async e30s(@graphql.Args() args: E30FindManyArgs): Promise<E30[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E30, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E30",
    action: "read",
    possession: "own",
  })
  async e30(@graphql.Args() args: E30FindUniqueArgs): Promise<E30 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E30)
  @nestAccessControl.UseRoles({
    resource: "E30",
    action: "delete",
    possession: "any",
  })
  async deleteE30(@graphql.Args() args: DeleteE30Args): Promise<E30 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
