/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE36Args } from "./DeleteE36Args";
import { E36FindManyArgs } from "./E36FindManyArgs";
import { E36FindUniqueArgs } from "./E36FindUniqueArgs";
import { E36 } from "./E36";
import { E36Service } from "../e36.service";

@graphql.Resolver(() => E36)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E36ResolverBase {
  constructor(
    protected readonly service: E36Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E36",
    action: "read",
    possession: "any",
  })
  async _e36sMeta(
    @graphql.Args() args: E36FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E36])
  @nestAccessControl.UseRoles({
    resource: "E36",
    action: "read",
    possession: "any",
  })
  async e36s(@graphql.Args() args: E36FindManyArgs): Promise<E36[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E36, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E36",
    action: "read",
    possession: "own",
  })
  async e36(@graphql.Args() args: E36FindUniqueArgs): Promise<E36 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E36)
  @nestAccessControl.UseRoles({
    resource: "E36",
    action: "delete",
    possession: "any",
  })
  async deleteE36(@graphql.Args() args: DeleteE36Args): Promise<E36 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
