/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE50Args } from "./DeleteE50Args";
import { E50FindManyArgs } from "./E50FindManyArgs";
import { E50FindUniqueArgs } from "./E50FindUniqueArgs";
import { E50 } from "./E50";
import { E50Service } from "../e50.service";

@graphql.Resolver(() => E50)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E50ResolverBase {
  constructor(
    protected readonly service: E50Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E50",
    action: "read",
    possession: "any",
  })
  async _e50sMeta(
    @graphql.Args() args: E50FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E50])
  @nestAccessControl.UseRoles({
    resource: "E50",
    action: "read",
    possession: "any",
  })
  async e50s(@graphql.Args() args: E50FindManyArgs): Promise<E50[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E50, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E50",
    action: "read",
    possession: "own",
  })
  async e50(@graphql.Args() args: E50FindUniqueArgs): Promise<E50 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E50)
  @nestAccessControl.UseRoles({
    resource: "E50",
    action: "delete",
    possession: "any",
  })
  async deleteE50(@graphql.Args() args: DeleteE50Args): Promise<E50 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
