/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE68Args } from "./DeleteE68Args";
import { E68FindManyArgs } from "./E68FindManyArgs";
import { E68FindUniqueArgs } from "./E68FindUniqueArgs";
import { E68 } from "./E68";
import { E68Service } from "../e68.service";

@graphql.Resolver(() => E68)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E68ResolverBase {
  constructor(
    protected readonly service: E68Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E68",
    action: "read",
    possession: "any",
  })
  async _e68sMeta(
    @graphql.Args() args: E68FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E68])
  @nestAccessControl.UseRoles({
    resource: "E68",
    action: "read",
    possession: "any",
  })
  async e68s(@graphql.Args() args: E68FindManyArgs): Promise<E68[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E68, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E68",
    action: "read",
    possession: "own",
  })
  async e68(@graphql.Args() args: E68FindUniqueArgs): Promise<E68 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E68)
  @nestAccessControl.UseRoles({
    resource: "E68",
    action: "delete",
    possession: "any",
  })
  async deleteE68(@graphql.Args() args: DeleteE68Args): Promise<E68 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
