/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE6Args } from "./DeleteE6Args";
import { E6FindManyArgs } from "./E6FindManyArgs";
import { E6FindUniqueArgs } from "./E6FindUniqueArgs";
import { E6 } from "./E6";
import { E6Service } from "../e6.service";

@graphql.Resolver(() => E6)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E6ResolverBase {
  constructor(
    protected readonly service: E6Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E6",
    action: "read",
    possession: "any",
  })
  async _e6sMeta(
    @graphql.Args() args: E6FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E6])
  @nestAccessControl.UseRoles({
    resource: "E6",
    action: "read",
    possession: "any",
  })
  async e6s(@graphql.Args() args: E6FindManyArgs): Promise<E6[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E6, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E6",
    action: "read",
    possession: "own",
  })
  async e6(@graphql.Args() args: E6FindUniqueArgs): Promise<E6 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E6)
  @nestAccessControl.UseRoles({
    resource: "E6",
    action: "delete",
    possession: "any",
  })
  async deleteE6(@graphql.Args() args: DeleteE6Args): Promise<E6 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
