/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE23Args } from "./DeleteE23Args";
import { E23FindManyArgs } from "./E23FindManyArgs";
import { E23FindUniqueArgs } from "./E23FindUniqueArgs";
import { E23 } from "./E23";
import { E23Service } from "../e23.service";

@graphql.Resolver(() => E23)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E23ResolverBase {
  constructor(
    protected readonly service: E23Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E23",
    action: "read",
    possession: "any",
  })
  async _e23sMeta(
    @graphql.Args() args: E23FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E23])
  @nestAccessControl.UseRoles({
    resource: "E23",
    action: "read",
    possession: "any",
  })
  async e23s(@graphql.Args() args: E23FindManyArgs): Promise<E23[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E23, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E23",
    action: "read",
    possession: "own",
  })
  async e23(@graphql.Args() args: E23FindUniqueArgs): Promise<E23 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E23)
  @nestAccessControl.UseRoles({
    resource: "E23",
    action: "delete",
    possession: "any",
  })
  async deleteE23(@graphql.Args() args: DeleteE23Args): Promise<E23 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
