/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE22Args } from "./DeleteE22Args";
import { E22FindManyArgs } from "./E22FindManyArgs";
import { E22FindUniqueArgs } from "./E22FindUniqueArgs";
import { E22 } from "./E22";
import { E22Service } from "../e22.service";

@graphql.Resolver(() => E22)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E22ResolverBase {
  constructor(
    protected readonly service: E22Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E22",
    action: "read",
    possession: "any",
  })
  async _e22sMeta(
    @graphql.Args() args: E22FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E22])
  @nestAccessControl.UseRoles({
    resource: "E22",
    action: "read",
    possession: "any",
  })
  async e22s(@graphql.Args() args: E22FindManyArgs): Promise<E22[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E22, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E22",
    action: "read",
    possession: "own",
  })
  async e22(@graphql.Args() args: E22FindUniqueArgs): Promise<E22 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E22)
  @nestAccessControl.UseRoles({
    resource: "E22",
    action: "delete",
    possession: "any",
  })
  async deleteE22(@graphql.Args() args: DeleteE22Args): Promise<E22 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
