/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE14Args } from "./DeleteE14Args";
import { E14FindManyArgs } from "./E14FindManyArgs";
import { E14FindUniqueArgs } from "./E14FindUniqueArgs";
import { E14 } from "./E14";
import { E14Service } from "../e14.service";

@graphql.Resolver(() => E14)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E14ResolverBase {
  constructor(
    protected readonly service: E14Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E14",
    action: "read",
    possession: "any",
  })
  async _e14sMeta(
    @graphql.Args() args: E14FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E14])
  @nestAccessControl.UseRoles({
    resource: "E14",
    action: "read",
    possession: "any",
  })
  async e14s(@graphql.Args() args: E14FindManyArgs): Promise<E14[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E14, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E14",
    action: "read",
    possession: "own",
  })
  async e14(@graphql.Args() args: E14FindUniqueArgs): Promise<E14 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E14)
  @nestAccessControl.UseRoles({
    resource: "E14",
    action: "delete",
    possession: "any",
  })
  async deleteE14(@graphql.Args() args: DeleteE14Args): Promise<E14 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
