/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE34Args } from "./DeleteE34Args";
import { E34FindManyArgs } from "./E34FindManyArgs";
import { E34FindUniqueArgs } from "./E34FindUniqueArgs";
import { E34 } from "./E34";
import { E34Service } from "../e34.service";

@graphql.Resolver(() => E34)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E34ResolverBase {
  constructor(
    protected readonly service: E34Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E34",
    action: "read",
    possession: "any",
  })
  async _e34sMeta(
    @graphql.Args() args: E34FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E34])
  @nestAccessControl.UseRoles({
    resource: "E34",
    action: "read",
    possession: "any",
  })
  async e34s(@graphql.Args() args: E34FindManyArgs): Promise<E34[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E34, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E34",
    action: "read",
    possession: "own",
  })
  async e34(@graphql.Args() args: E34FindUniqueArgs): Promise<E34 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E34)
  @nestAccessControl.UseRoles({
    resource: "E34",
    action: "delete",
    possession: "any",
  })
  async deleteE34(@graphql.Args() args: DeleteE34Args): Promise<E34 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
