/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteE39Args } from "./DeleteE39Args";
import { E39FindManyArgs } from "./E39FindManyArgs";
import { E39FindUniqueArgs } from "./E39FindUniqueArgs";
import { E39 } from "./E39";
import { E39Service } from "../e39.service";

@graphql.Resolver(() => E39)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class E39ResolverBase {
  constructor(
    protected readonly service: E39Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "E39",
    action: "read",
    possession: "any",
  })
  async _e39sMeta(
    @graphql.Args() args: E39FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [E39])
  @nestAccessControl.UseRoles({
    resource: "E39",
    action: "read",
    possession: "any",
  })
  async e39s(@graphql.Args() args: E39FindManyArgs): Promise<E39[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => E39, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "E39",
    action: "read",
    possession: "own",
  })
  async e39(@graphql.Args() args: E39FindUniqueArgs): Promise<E39 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => E39)
  @nestAccessControl.UseRoles({
    resource: "E39",
    action: "delete",
    possession: "any",
  })
  async deleteE39(@graphql.Args() args: DeleteE39Args): Promise<E39 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
